# shared configuration for all applications
spring:
    cloud:
        consul:
            host: localhost
            port: 8500
            discovery:
                healthCheckPath: ${management.contextPath}/health
                healthCheckInterval: 15s
                instanceId: ${spring.application.name}:${random.value}
    main:
        banner-mode: console
    groovy:
        template:
            check-template-location: false
    jackson:
        serialization:
            indent_output: true
        serialization-inclusion: non_empty
    rabbitmq:
        host: localhost
        port: 5672
        virtualHost: /
        username: guest
        password: guest

management:
    context-path: /operations

endpoints:
    health:
        sensitive: false
        health.time-to-live: 1000

server:
  port: 8080
  contextPath: /

logging:
  config: classpath:logback.xml

info:
  app:
    name: ${name}
    description: ${description}
    version: ${version}

security:
  user:
    name: developer
    password: developer
  basic:
    enabled: false
    realm: example
