# shared configuration for all applications
applications: consulhystrixclient
endpoints:
    health:
        time-to-live: 1000
        sensitive: false
logging:
    config: classpath:logback.xml
management:
    contextPath: /operations
    security:
        enabled: false
        role: admin
        sessions: stateless
security:
    user:
        name: developer
        password: developer
    basic:
        enabled: false
        realm: example
server:
    contextPath: /
    port: 8080
    useForwardHeaders: true
    tomcat:
        portHeader: X-Forwarded-Port
        protocolHeader: X-Forwarded-Protocol-Header
        remoteIpHeader: X-Forwarded-Remote-IP-Header
spring:
    cloud:
        consul:
            host: localhost
            port: 8500
            discovery:
                healthCheckInterval: 15s
                healthCheckPath: ${management.contextPath}/health
                instanceId: ${spring.application.name}:${random.value}
                preferAgentAddress: true
                preferIpAddress: true
    groovy:
        template:
            check-template-location: false
    inetutils:
        timeoutSeconds: 1
        defaultHostname: localhost
        localhost: 127.0.0.1
        ignoredInterfaces:
            - docker0
    jackson:
        serialization:
            indent_output: true
        serialization-inclusion: non_empty
    main:
        banner-mode: console
    rabbitmq:
        host: localhost
        password: guest
        port: 5672
        virtualHost: /
        username: guest
turbine:
    aggregator:
        clusterConfig: ${applications}
    appConfig: ${applications}