# shared configuration for all applications
endpoints:
    health:
        time-to-live: 1000
        sensitive: false
info:
    app:
        name: ${name}
        description: ${description}
        version: ${version}
logging:
    config: classpath:logback.xml
management:
    context-path: /operations
    security:
        enabled: false
        role: admin
        sessions: stateless
security:
    user:
        name: developer
        password: developer
    basic:
        enabled: false
        realm: example
server:
    port: 8080
    contextPath: /
spring:
    cloud:
        consul:
            host: localhost
            port: 8500
            discovery:
                healthCheckPath: ${management.contextPath}/health
                healthCheckInterval: 15s
                instanceId: ${spring.application.name}:${random.value}
    groovy:
        template:
            check-template-location: false
    jackson:
        serialization:
            indent_output: true
        serialization-inclusion: non_empty
    main:
        banner-mode: console
    rabbitmq:
        host: localhost
        password: guest
        port: 5672
        virtualHost: /
        username: guest
