#shared configuration for all Spring Boot based applications
---
spring:
    cloud:
        config:
#           uri: http://consul:8080
            server:
                health:
                    # there is a bug/feature where the hitting the health endpoint causes the server to refresh with Git
                    # https://github.com/spring-cloud/spring-cloud-config/issues/423
                    enabled: false
        consul:
            host: consul
            port: 8500
            discovery:
                healthCheckInterval: 15s
                healthCheckPath: ${management.contextPath}/health
                instanceId: ${spring.application.name}:${random.int[1,65536]}
                port: ${server.port}
                preferAgentAddress: true
                preferIpAddress: true
                serviceName: ${spring.application.name}
    main:
        banner-mode: console
    groovy:
        template:
            check-template-location: false
    jackson:
        serialization:
            indent_output: true
        serialization-inclusion: non_empty

management:
    contextPath: /operations
    security:
        enabled: false
        role: admin
        sessions: stateless

# configure operations endpoints
endpoints:
    health:
        time-to-live: 1000
        sensitive: false

server:
    contextPath: /
    port: 8080
    useForwardHeaders: true
    tomcat:
        portHeader: X-Forwarded-Port
        protocolHeader: X-Forwarded-Protocol-Header
        remoteIpHeader: X-Forwarded-Remote-IP-Header

# which logback configuration file to use
logging:
  config: classpath:logback.xml

# Override the default security properties, defined in org.springframework.boot.autoconfigure.security.SecurityProperties
security:
  user:
    name: operations
    password: operations
  basic:
    enabled: false
    realm: example
