---
producer:
    foo: default
    serviceCode: ${spring.application.name}
    serviceInstance: ${random.int[1,65536]}
    realm: development

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
