consumer:
    foo: default
    serviceCode: ${spring.application.name}
    serviceInstance: ${random.int[1,65536]}
    realm: development
    fail: false

spring:
    cloud:
        stream:
            bindings:
                input:
                    destination: rendezous
                    group: example
                    contentType: text/plain
                    consumer:
                        concurrency: 1
                        partitioned: false
                        maxAttempts: 3
                        backOffInitialInterval: 1000
                        backOffMaxInterval: 10000
                        backOffMultiplier: 2.0
                        acknowledgeMode: AUTO
                        autoBindDlq: true
                        durableSubscription: true
                        maxConcurrency: 1
                        prefetch: 1
                        prefix: ${spring.application.name}.
                        requeueRejected: true
                        republishToDlq: true
                        transacted: false
                        txSize: 1