producer:
    foo: home
    serviceCode: ${spring.application.name}
    serviceInstance: ${random.int[1,65536]}
    realm: home
    fail: false

spring:
    cloud:
        consul:
            discovery:
                enabled: false
                register: false
    rabbitmq:
        host: 192.168.1.229
    datasource:
        url: jdbc:mysql://192.168.1.229/tlo
        username: mysql
        password: mysql
